#
# SMARTLink Easy Setup for LuCI
# Copyright (C) 2026 Alagha Technology
#
# This is free software, licensed under the Apache License, Version 2.0 .
#

include $(TOPDIR)/rules.mk

LUCI_TITLE:=SMARTLink Easy Setup
LUCI_DESCRIPTION:=Single-page commissioning for mode, internet connection and Wi-Fi
LUCI_DEPENDS:=+luci-base
LUCI_PKGARCH:=all

PKG_VERSION:=1.1.2
PKG_LICENSE:=Apache-2.0
PKG_MAINTAINER:=Alagha Technology

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
