#!/bin/sh

changed=0

set_opt() {
	local key=$1
	local val=$2

	if ! uci -q get "luci.$key" >/dev/null 2>&1; then
		uci set "luci.$key=$val"
		changed=1
	fi
}

set_opt themes.SMARTLink /luci-static/smartlink

# Make SMARTLink the active theme on first install (not on package upgrade).
if [ "$PKG_UPGRADE" != 1 ] && [ $changed = 1 ]; then
	uci set luci.main.mediaurlbase=/luci-static/smartlink
	changed=1
fi

if [ $changed = 1 ]; then
	uci commit luci
fi

exit 0
